#!/bin/bash

# setup_env.sh - Setup environment variables for the project
# This script helps configure the project using environment variables

echo "Setting up environment variables..."

# Check if .env file exists, if not create it with template
if [ ! -f ".env" ]; then
    echo "Creating .env file from template..."
    cat > .env << 'EOL'
# Environment Configuration
# Copy this file to .env and update the paths according to your system

# Java Development Kit (JDK) path
# Example: /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
export JAVA_HOME="${JAVA_HOME}"

# Android SDK path
# Example: /Users/username/Library/Android/sdk
export ANDROID_HOME="${ANDROID_HOME}"

# Flutter SDK path (if not in PATH)
# Example: /Users/username/flutter
export FLUTTER_ROOT="${FLUTTER_ROOT}"

# Add Android SDK platform-tools to PATH
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/tools/bin"

# For macOS Intel
if [ "$(uname -m)" = "x86_64" ]; then
    export PATH="$PATH:$ANDROID_HOME/emulator"
fi

# For macOS Apple Silicon
if [ "$(uname -m)" = "arm64" ]; then
    export PATH="$PATH:$ANDROID_HOME/emulator"
fi
EOL
    echo "Created .env file. Please update the paths according to your system."
    echo "Don't forget to add .env to your .gitignore file!"
else
    echo ".env file already exists. Updating with current environment variables..."
    # Update existing .env with current environment variables
    sed -i '' "s|export JAVA_HOME=.*|export JAVA_HOME=\"${JAVA_HOME}\"|" .env
    sed -i '' "s|export ANDROID_HOME=.*|export ANDROID_HOME=\"${ANDROID_HOME}\"|" .env
    sed -i '' "s|export FLUTTER_ROOT=.*|export FLUTTER_ROOT=\"${FLUTTER_ROOT}\"|" .env
fi

# Create or update local.properties for Android
echo "Configuring Android local.properties..."
cat > android/local.properties << EOL
## This file is automatically generated by setup_env.sh
## It contains machine-specific configuration and should not be tracked by version control
##
## To update these settings, run: source setup_env.sh
sdk.dir=$ANDROID_HOME
EOL

# Make the script executable
chmod +x setup_env.sh

echo ""
echo "Setup complete!"
echo "1. Please review the .env file and update any paths if needed"
echo "2. Run 'source .env' to apply the environment variables to your current session"
echo "3. For future sessions, add 'source /path/to/project/.env' to your shell profile (e.g., ~/.zshrc or ~/.bash_profile)"
